2017-05-24 15:08:49.980 - info: service : /mongo/api/v1/client
2017-05-24 15:08:50.113 - info: service : /mongo/api/v1/client
2017-05-24 15:14:36.353 - info: service : /mongo/api/v1/client
2017-05-24 15:14:36.358 - info: service : /mongo/api/v1/client
2017-05-24 15:14:39.841 - info: service : /mongo/api/v1/client
2017-05-24 15:14:39.845 - info: service : /mongo/api/v1/client
2017-05-24 16:02:28.911 - info: service : /mongo/api/v1/client
2017-05-24 16:02:28.915 - info: service : /mongo/api/v1/client
2017-05-24 16:02:30.101 - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017] date=Wed May 24 2017 16:02:30 GMT-0500 (Hora est. Pacífico, Sudamérica), pid=9660, uid=null, gid=null, cwd=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate, execPath=D:\nodejs-6.9.4\node.exe, version=v6.9.4, argv=[D:\nodejs-6.9.4\node.exe, E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\server.js], rss=50360320, heapTotal=35688448, heapUsed=23510912, loadavg=[0, 0, 0], uptime=20937.0877451, trace=[column=35, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=274, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=177, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=emitErrorNT, line=1278, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js:274:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js:177:49),     at Socket.g (events.js:291:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at emitErrorNT (net.js:1278:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
2017-05-24 16:03:35.550 - info: service : /mongo/api/v1/client
2017-05-24 16:03:35.554 - info: service : /mongo/api/v1/client
2017-05-24 16:07:35.796 - info: service : /mongo/api/v1/client
2017-05-24 16:07:35.800 - info: service : /mongo/api/v1/client
2017-05-25 12:55:14.984 - info: service : /mongo/api/v1/client
2017-05-25 12:55:14.988 - info: service : /mongo/api/v1/client
2017-05-25 12:55:16.061 - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017] date=Thu May 25 2017 12:55:16 GMT-0500 (Hora est. Pacífico, Sudamérica), pid=5108, uid=null, gid=null, cwd=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate, execPath=D:\nodejs-6.9.4\node.exe, version=v6.9.4, argv=[D:\nodejs-6.9.4\node.exe, E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\server.js], rss=50900992, heapTotal=35688448, heapUsed=23421160, loadavg=[0, 0, 0], uptime=96103.0481402, trace=[column=35, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=274, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=177, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=emitErrorNT, line=1278, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js:274:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js:177:49),     at Socket.g (events.js:291:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at emitErrorNT (net.js:1278:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
