2017-05-19 12:29:20.100 - info: service : /api/v1/operation
2017-05-19 12:29:20.105 - info: service : /api/v1/operation
2017-05-19 12:29:20.139 - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017] date=Fri May 19 2017 12:29:20 GMT-0500 (Hora est. Pacífico, Sudamérica), pid=2412, uid=null, gid=null, cwd=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate, execPath=D:\nodejs-7.2.1\node.exe, version=v7.2.1, argv=[D:\nodejs-7.2.1\node.exe, E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\server.js], rss=56074240, heapTotal=37728256, heapUsed=26196984, external=18591679, loadavg=[0, 0, 0], uptime=139388.2606942, trace=[column=35, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=274, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=177, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=connectErrorNT, line=1025, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017],     at Pool.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js:274:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js:177:49),     at Socket.g (events.js:292:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at connectErrorNT (net.js:1025:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
2017-05-19 13:16:19.025 - info: service : /api/v1/operation
2017-05-19 13:16:19.031 - info: service : /api/v1/operation
2017-05-19 13:16:20.092 - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017] date=Fri May 19 2017 13:16:20 GMT-0500 (Hora est. Pacífico, Sudamérica), pid=24556, uid=null, gid=null, cwd=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate, execPath=D:\nodejs-7.2.1\node.exe, version=v7.2.1, argv=[D:\nodejs-7.2.1\node.exe, E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\server.js], rss=51994624, heapTotal=37728256, heapUsed=23002904, external=18588976, loadavg=[0, 0, 0], uptime=142208.2130672, trace=[column=35, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=274, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=177, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=emitErrorNT, line=1281, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js:274:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js:177:49),     at Socket.g (events.js:292:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at emitErrorNT (net.js:1281:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
