2017-05-23 16:44:25.294 - info: service : /mongo/api/v1/client
2017-05-23 16:44:25.301 - info: service : /mongo/api/v1/client
2017-05-23 16:44:26.332 - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017] date=Tue May 23 2017 16:44:26 GMT-0500 (Hora est. Pacífico, Sudamérica), pid=10176, uid=null, gid=null, cwd=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate, execPath=D:\nodejs-7.2.1\node.exe, version=v7.2.1, argv=[D:\nodejs-7.2.1\node.exe, E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\server.js], rss=48078848, heapTotal=34582528, heapUsed=17551360, external=17895277, loadavg=[0, 0, 0], uptime=51174.8292515, trace=[column=35, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=274, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=177, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=emitErrorNT, line=1281, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js:274:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js:177:49),     at Socket.g (events.js:292:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at emitErrorNT (net.js:1281:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
2017-05-23 16:45:02.676 - info: service : /mongo/api/v1/client
2017-05-23 16:45:02.682 - info: service : /mongo/api/v1/client
2017-05-23 16:45:03.723 - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017] date=Tue May 23 2017 16:45:03 GMT-0500 (Hora est. Pacífico, Sudamérica), pid=10280, uid=null, gid=null, cwd=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate, execPath=D:\nodejs-7.2.1\node.exe, version=v7.2.1, argv=[D:\nodejs-7.2.1\node.exe, E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\server.js], rss=48037888, heapTotal=34582528, heapUsed=17556008, external=17895277, loadavg=[0, 0, 0], uptime=51212.2194615, trace=[column=35, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=274, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=177, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=emitErrorNT, line=1281, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js:274:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js:177:49),     at Socket.g (events.js:292:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at emitErrorNT (net.js:1281:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
