2017-05-25 12:56:36.577 - info: service : /mongo/api/v1/client
2017-05-25 12:56:36.582 - info: service : /mongo/api/v1/client
2017-05-25 12:56:37.925 - error: uncaughtException: failed to connect to server [54.157.43.222:27017] on first connect [MongoError: connect ECONNREFUSED 54.157.43.222:27017] date=Thu May 25 2017 12:56:37 GMT-0500 (Hora est. Pacífico, Sudamérica), pid=14856, uid=null, gid=null, cwd=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate, execPath=D:\nodejs-6.9.4\node.exe, version=v6.9.4, argv=[D:\nodejs-6.9.4\node.exe, E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\server.js], rss=50769920, heapTotal=35688448, heapUsed=23424064, loadavg=[0, 0, 0], uptime=96184.9137076, trace=[column=35, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=274, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=177, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=emitErrorNT, line=1278, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [54.157.43.222:27017] on first connect [MongoError: connect ECONNREFUSED 54.157.43.222:27017],     at Pool.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js:274:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js:177:49),     at Socket.g (events.js:291:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at emitErrorNT (net.js:1278:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
2017-05-25 12:56:55.767 - info: service : /mongo/api/v1/client
2017-05-25 12:56:55.770 - info: service : /mongo/api/v1/client
2017-05-25 12:56:56.804 - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017] date=Thu May 25 2017 12:56:56 GMT-0500 (Hora est. Pacífico, Sudamérica), pid=12180, uid=null, gid=null, cwd=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate, execPath=D:\nodejs-6.9.4\node.exe, version=v6.9.4, argv=[D:\nodejs-6.9.4\node.exe, E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\server.js], rss=50733056, heapTotal=35688448, heapUsed=23421504, loadavg=[0, 0, 0], uptime=96203.7920928, trace=[column=35, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=274, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=177, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=emitErrorNT, line=1278, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\pool.js:274:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (E:\ingeneo\proyectos\nodejs_guate\api_express_mongo_demo_guate\node_modules\mongodb-core\lib\connection\connection.js:177:49),     at Socket.g (events.js:291:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at emitErrorNT (net.js:1278:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
